* Sharedb-ace
[[https://badge.fury.io/js/sharedb-ace.svg]]

Sharedb-ace provides two-way bindings between [[https://github.com/share/sharedb][ShareDB]] and [[http://ace.c9.io/][Ace Editor]].

** Installation
Using npm:

#+BEGIN_SRC sh
npm install sharedb-ace
#+END_SRC

Using pre-compiled js from unpkg CDN:

#+BEGIN_SRC html
  <script src="https://unpkg.com/sharedb-ace@latest/dist/sharedb-ace.min.js"></script>
#+END_SRC

** Documentation
Please see [[http://www.jethrokuan.com/sharedb-ace/][here]] for internals documentation.

*** Single Ace-editor Instance
Setup the ShareDB document as a string:
#+BEGIN_SRC js
  ShareAce.on('ready', function() {
    ShareAce.add(editor, [], [ Plugins, Here ]);
  });
#+END_SRC

*** Multiple Ace-editor Instances
Your setup may be more complex, and requires the use of multiple ace-instances synchronized over one connection. Setup the ShareDB document to be a JSON object.

For example:
#+BEGIN_SRC js
{
  "foo": "",
  "bar": ""
}

Next, connect the two paths to two separate ace editor instances:
#+BEGIN_SRC js
ShareAce.on('ready', function() {
  ShareAce.add(editor1, ["foo"], []);
  ShareAce.add(editor2, ["bar"], []);
});
#+END_SRC

** Developing sharedb-ace
1. Fork or clone this repo:
#+BEGIN_SRC sh
git clone https://github.com/jethrokuan/sharedb-ace.git
#+END_SRC

#+BEGIN_SRC sh
cd sharedb-ace && npm install
#+END_SRC

*** Generating JS Docs
We generate javascript documentation using inline documentation.

#+BEGIN_SRC sh
jsdoc source/*.js --destination ./docs/
#+END_SRC

*** License
#+BEGIN_QUOTE
Copyright 2019 Jethro Kuan

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+END_QUOTE

